In [3]:
import numpy as np
import pandas as pd

data = pd.read_csv("data/movie.csv")
data.head()

Unnamed: 0                         name  \
0           0                    Toy Story   
1           1                      Jumanji   
2           2             Grumpier Old Men   
3           3            Waiting to Exhale   
4           4  Father of the Bride Part II   

                               genres      budget      revenue  runtime  \
0   ['Animation', 'Comedy', 'Family']  30000000.0  373554033.0     81.0   
1  ['Adventure', 'Fantasy', 'Family']  65000000.0  262797249.0    104.0   
2               ['Romance', 'Comedy']         0.0          0.0    101.0   
3      ['Comedy', 'Drama', 'Romance']  16000000.0   81452156.0    127.0   
4                          ['Comedy']         0.0   76578911.0    106.0   

   popularity  vote_counts  vote_averages  
0   21.946943       5415.0            7.7  
1   17.015539       2413.0            6.9  
2   11.712900         92.0            6.5  
3    3.859495         34.0            6.1  
4    8.387519        173.0            5.7

In [53]:
arr = data.to_numpy()
data = arr[:,1:]

In [68]:
data[1][1].replace("Fantasy","1")
st = data[1][1].replace("[","")
s1 = st.replace("]","")

In [69]:
s1

"'Adventure', 'Fantasy', 'Family'"

In [50]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import neighbors, datasets

iris = datasets.load_iris()
iris_X = iris.data
iris_y = iris.target
print('Number of classes: %d' %len(np.unique(iris_y)))
print('Number of data points: %d' %len(iris_y))


X0 = iris_X[iris_y == 0,:]
print('\nSamples from class 0:\n', X0[:5,:])

X1 = iris_X[iris_y == 1,:]
print('\nSamples from class 1:\n', X1[:5,:])

X2 = iris_X[iris_y == 2,:]
print('\nSamples from class 2:\n', X2[:5,:])

Number of classes: 3
Number of data points: 150

Samples from class 0:
 [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]

Samples from class 1:
 [[7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.9 1.5]
 [5.5 2.3 4.  1.3]
 [6.5 2.8 4.6 1.5]]

Samples from class 2:
 [[6.3 3.3 6.  2.5]
 [5.8 2.7 5.1 1.9]
 [7.1 3.  5.9 2.1]
 [6.3 2.9 5.6 1.8]
 [6.5 3.  5.8 2.2]]
