In [6]:
# To support both python 2 and python 3
from __future__ import division, print_function, unicode_literals
import numpy as np 
import matplotlib
import matplotlib.pyplot as plt
import pandas as pd
import time
import random
### Get data from CSV file
data = pd.read_csv("data/Admission_Predict.csv")
arr = data.to_numpy()
arr2 = arr[:,1:].T
print(arr2.T)
### Normalise data
arr2[0] = (arr2[0] - arr2[0].min())/(arr2[0].ptp())
arr2[1] = (arr2[1] - arr2[1].min())/(arr2[1].ptp())
arr2 = arr2.T
print(arr2)

[[337.   118.     4.   ...   9.65   1.     0.92]
 [324.   107.     4.   ...   8.87   1.     0.76]
 [316.   104.     3.   ...   8.     1.     0.72]
 ...
 [330.   116.     4.   ...   9.45   1.     0.91]
 [312.   103.     3.   ...   8.78   0.     0.67]
 [333.   117.     4.   ...   9.66   1.     0.95]]
[[0.94       0.92857143 4.         ... 9.65       1.         0.92      ]
 [0.68       0.53571429 4.         ... 8.87       1.         0.76      ]
 [0.52       0.42857143 3.         ... 8.         1.         0.72      ]
 ...
 [0.8        0.85714286 4.         ... 9.45       1.         0.91      ]
 [0.44       0.39285714 3.         ... 8.78       0.         0.67      ]
 [0.86       0.89285714 4.         ... 9.66       1.         0.95      ]]


In [7]:
shuffled_data = arr2.T[:, np.random.permutation(arr2.T.shape[1])].T ### Shuffle data
training_data = shuffled_data[0:300] ### Get data used for training
testing_data = shuffled_data[300:]   ### Get data used for testing

training_input = training_data[:,:-1]   ### Input training data
training_output = training_data[:,-1:]   ### Output training data
testing_input = testing_data[:,:-1]
testing_output = testing_data[:,-1:]

In [8]:
class Linear_Regression():
    def __init__(self,x,w,y,learning_rate = 0.0001):
        self.X = x
        self.y = y
        self.w = w
        self.learning_rate = learning_rate
        self.N = len(self.y)
    def loss(self):
        sum = float(0)
        sum = np.linalg.norm((self.X .dot(self.w) - self.y))
        return sum**2/(2*self.N)
    def grad(self):
        return (self.X.T .dot(self.X .dot(self.w) - self.y)) / self.N
    def grad_Descent(self):
        it = float(0)
        lst = list()
        while it < 100000:
            if self.loss() < 1e-3:
                break
            lst.append(self.loss())
            self.w = self.w - self.learning_rate*self.grad()
            it = it + 1
        return lst,it

In [9]:
w = np.zeros((7,1))
trainer = Linear_Regression(training_input,w,training_output,0.0001)
lst,it = trainer.grad_Descent()
print("vector W after training: ")
print(trainer.w)
print("Loss: %.8f after %.0f iterations " %(trainer.loss(),it))

tester = Linear_Regression(testing_input, trainer.w, testing_output)
print("Loss got by tester: %.8f" %(tester.loss()))

from sklearn import datasets, linear_model
regr = linear_model.LinearRegression(fit_intercept=False) # fit_intercept = False for calculating the bias
regr.fit(training_input, training_output)

# Compare two results
print( 'Solution found by scikit-learn  : ', regr.coef_ )
train = Linear_Regression(training_input,regr.coef_.T,training_output)
print("Loss: %.8f" %(train.loss()))

vector W after training: 
[[0.0537784 ]
 [0.04777971]
 [0.02616842]
 [0.00720882]
 [0.02957685]
 [0.05034263]
 [0.04615619]]
Loss: 0.00266265 after 100000 iterations 
Loss got by tester: 0.00187393
Solution found by scikit-learn  :  [[ 0.15322558  0.13341891  0.01146322 -0.00102859  0.02974777  0.04835522
   0.02829687]]
Loss: 0.00233921
